### ISSUE TITLE
请问怎么下载标注好意图和行为的EOT数据集

### ISSUE THREAD

**Issue by caoyaru123** [Sea94/EQT#1]
作者您好，请问怎么下载标注好意图和行为的EOT数据集，谢谢

**Comment by Sea94** [comment]
Hello,
You can find it in the annotations folder: https://github.com/Sea94/EQT/tree/master/annotations

**Comment by caoyaru123** [comment]
非常非常感谢您的分享。不好意思还有一个问题是，点击download后挑战的网页的形式，可以直接下载文件吗？谢谢您
![image](https://user-images.githubusercontent.com/121163561/222109266-f36acafe-a07c-4477-8f6e-34b16f36d729.png)
